Lab_Bago/urls.py
from django.contrib import admin
from django.urls import path, include

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('authentication.urls')),
    path('externos/', include('external_workers.urls')),
    path('internos/', include('internal_workers.urls')),
    path('mant_preventivo/', include('mant_preventivo.urls')),
    path('sentry-debug/', trigger_error),
]

app/urls.py
from django.urls import path
from django.conf.urls import handler404
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from axes.decorators import axes_dispatch


urlpatterns = [
    path('', home, name="home"),
    path('base/', base, name="base"),
    #path('logout/', cerrar_session, name="logout"),

    #path('auth/login/', axes_dispatch(iniciar_session), name="login"),
    #path('auth/registro/', registro, name="registro"),
    path('auth/roles/', roles, name='roles'),
    





    #path('infraestructura/crear_solicitud/', crear_solicitud_externo, name='crear_solicitud'),
    #path('infraestructura/presupuesto/<int:tarea_id>/', cargar_presupuesto, name='gestionar_presupuesto'),
    #path('infraestructura/reporte_externo/<int:tarea_id>/', reporte_externo, name='reporte_externo'),
    #path('infraestructura/feedback_externo/<int:tarea_id>/', feedback_externo, name='feedback_externo'),

    #path('api/user/<int:user_id>/', obtener_datos_usuario, name='obtener_datos_usuario'),

    path('dashboard/graficos', graficos, name='graficos'),
    path('descargar-tareas/', descargar_tareas, name='descargar_tareas'),

    #path('dashboard/listar_tareas', listar_tareas, name='listar_tareas'),
    #path('dashboard/listar_solicitudes', listar_solicitudes, name='listar_solicitudes'),

    #path('notificaciones/', notificaciones, name='notificaciones'),
    #path('notificaciones/<int:notificaciones_id>/', notificaciones_id , name='notificaciones_id'),
    #path('notificacion/marcar_leida/<int:notificacion_id>/', marcar_notificacion_leida, name='marcar_notificacion_leida'),



    #path('detalle/informe/<int:informe_id>/', detalle_informe, name='detalle_informe'),
    #path('detalle/reporte/<int:reporte_id>/', detalle_reporte, name='detalle_reporte'),
    #path('detalle/feedback/<int:feedback_id>/', detalle_feedback, name='detalle_feedback'),

    #path('detalle_externo/solicitud/<int:solicitud_id>/', detalle_solicitud, name='detalle_solicitud'),
    #path('detalle_externo/presupuesto_ext/<int:presupuesto_id>/', detalle_presupuesto, name='detalle_presupuesto'),
    #path('detalle_externo/reporte_ext/<int:reporte_ex_id>/', detalle_reporte_ex, name='detalle_reporte_ext'),
    #path('detalle_externo/feedback_ext/<int:feedback_ex_id>/', detalle_feedbacks_ex, name='detalle_feedback_ext'),

    path('app/error/404', error_404, name='error_404'),
    path('app/error/403', error_403, name='error_403'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = error_404
handler403 = error_403

external_workers/models.py
from django.db import models
from django.contrib.auth.models import User


# Externos

class SolicitudExterno(models.Model):
    externo = models.ForeignKey(User, on_delete=models.CASCADE, related_name='solicitudes_externas')
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    objetivo = models.CharField(max_length=200, null=False, blank=False)
    descripcion = models.TextField(null=False, blank=False)
    imagen = models.ImageField(upload_to='ex_peticiones_imagenes/', null=False, blank=False)
    pdf_peticion = models.FileField(upload_to='ex_peticiones/', null=False, blank=False)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            TareaExterno.objects.create(solicitud=self)

    def __str__(self):
        return f"Solicitud a {self.externo.username} - {self.fecha_creacion}"

class TareaExterno(models.Model):
    solicitud = models.ForeignKey(SolicitudExterno, on_delete=models.CASCADE, related_name='tareas_externas')
    estado = models.CharField(
        max_length=20,
        choices=[('en_espera', 'En Espera'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('rechazada', 'Rechazada')],
        default='en_espera'
    )
    fecha_asistencia = models.DateField(null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def actualizar_estado(self, nuevo_estado):
        self.estado = nuevo_estado
        self.save()

    def __str__(self):
        return f"Tarea de {self.solicitud.externo.username} - {self.estado}"

class PresupuestoExterno(models.Model):
    tarea_externo = models.OneToOneField(TareaExterno, on_delete=models.CASCADE, related_name='presupuesto_externo')
    archivo = models.FileField(upload_to='ex_presupuestos/', blank=False)
    fecha_asistencia = models.DateField(null=True, blank=True)
    estado = models.CharField(
        max_length=20,
        choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')],
        default='pendiente'
    )
    mensaje = models.TextField(blank=False, null=True)
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.fecha_asistencia:
            self.tarea_externo.fecha_asistencia = self.fecha_asistencia
            self.tarea_externo.save()
        self.tarea_externo.actualizar_estado('en_curso')

    def __str__(self):
        return f"Presupuesto de {self.tarea_externo.solicitud.externo.username} - Estado: {self.estado}"

class ExternoReporte(models.Model):
    tarea_externo = models.OneToOneField(TareaExterno, on_delete=models.CASCADE, related_name='externo_reportes')
    descripcion = models.TextField(blank=False, null=True)
    imagen = models.ImageField(upload_to='ex_reporte_imagenes/', blank=False, null=True)
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    def __str__(self):
        return f"Reporte de {self.tarea_externo.solicitud.externo.username} - {self.fecha_creacion}"

class ExternoFeedback(models.Model):
    tarea_externo = models.OneToOneField(TareaExterno, on_delete=models.CASCADE, related_name='externo_feedback')
    aprobado = models.BooleanField(blank=False)
    comentario = models.TextField(null=False, blank=True, default="Trabajo aprobado")
    fecha_creacion = models.DateTimeField(auto_now_add=True)
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        nuevo_estado = 'completada' if self.aprobado else 'rechazada'
        self.tarea_externo.actualizar_estado(nuevo_estado)

    def __str__(self):
        return f"Feedback de {self.creado_por.username} - {self.fecha_creacion}"
    

internal_workers/models.py
from django.db import models
from django.contrib.auth.models import User

class Zona(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
class UbicacionTecnica(models.Model):
    zona = models.ForeignKey(Zona, related_name='ubicaciones_tecnicas', on_delete=models.CASCADE)
    codigo = models.CharField(max_length=255)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.codigo} ({self.descripcion})"

class Equipo(models.Model):
    ubicacion_tecnica = models.ForeignKey(UbicacionTecnica, related_name='equipos', on_delete=models.CASCADE)
    codigo = models.CharField(max_length=255)
    descripcion = models.TextField(null=True, blank=True)


    def __str__(self):
        return f"{self.codigo} ({self.descripcion})"


class Estado(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

class Informe(models.Model):
    INFRAESTRUCTURA = 'INF'
    MAQUINARIA = 'MAQ'
    CATEGORIA_CHOICES = [
        (INFRAESTRUCTURA, 'Infraestructura'),
        (MAQUINARIA, 'Maquinaria'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="informes")
    creado_en = models.DateTimeField(auto_now_add=True)
    zona = models.ForeignKey(Zona, on_delete=models.SET_NULL, null=True)
    objetivo = models.TextField(null=True, blank=True)
    mensaje = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='informes/')
    categoría = models.CharField(max_length=3, choices=CATEGORIA_CHOICES, default=INFRAESTRUCTURA)
    ubicacion_tecnica = models.ForeignKey(UbicacionTecnica, on_delete=models.SET_NULL, null=True, blank=True)
    equipo = models.ForeignKey(Equipo, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['-creado_en']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not Tarea.objects.filter(informe=self).exists():
            Tarea.objects.create(informe=self, objetivo=self.objetivo)

    def __str__(self):
        return f'Informe: {self.objetivo}'

class Notificacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    informe = models.ForeignKey(Informe, on_delete=models.CASCADE)
    leido = models.BooleanField(default=False)
    creado_en = models.DateTimeField(auto_now_add=True)
    mensaje = models.TextField(null=True, blank=True)

    def marcar_como_leido(self):
        self.leido = True
        self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Tarea(models.Model):
    informe = models.ForeignKey(Informe, on_delete=models.CASCADE)
    objetivo = models.TextField(null=True, blank=True)
    estado = models.ForeignKey(Estado, on_delete=models.SET_NULL, null=True, blank=True)
    asignado_a = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="tareas")
    creado_en = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.estado:
            self.estado = Estado.objects.get(nombre='Pendiente')
        self.objetivo = self.informe.objetivo
        super().save(*args, **kwargs)

    def asignar_tecnico(self, tecnico):
        if self.asignado_a:
            Notificacion.objects.create(usuario=self.asignado_a, informe=self.informe, mensaje=f'Tarea reasignada: {self.objetivo}')
        
        self.asignado_a = tecnico
        self.save()
        Notificacion.objects.create(usuario=tecnico, informe=self.informe, mensaje=f'Tarea asignada: {self.objetivo}')

    def __str__(self):
        return f'Tarea: {self.objetivo} - Estado: {self.estado}'

class ReporteTarea(models.Model):
    tarea = models.OneToOneField(Tarea, on_delete=models.CASCADE, related_name='reporte_tarea')
    contenido = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='reportes_tarea/', blank=False)
    creado_en = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.tarea.estado = Estado.objects.get(nombre='Completada')
        self.tarea.save()
        super().save(*args, **kwargs)
        Notificacion.objects.create(
            usuario=self.tarea.informe.usuario,
            informe=self.tarea.informe,
            mensaje=f'Se ha creado un reporte para la tarea: {self.tarea.objetivo}'
        )

    def __str__(self):
        return f'Reporte de Tarea: {self.tarea.objetivo} - Fecha: {self.creado_en.strftime("%Y-%m-%d %H:%M")}'

class FeedbackTarea(models.Model):
    tarea = models.OneToOneField(Tarea, on_delete=models.CASCADE)
    aprobado = models.BooleanField()
    comentarios = models.TextField(null=False, blank=True, default="Trabajo aprobado")
    creado_en = models.DateTimeField(auto_now_add=True)
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.aprobado:
            self.tarea.estado = Estado.objects.get(nombre='Rechazada')
        else:
            self.tarea.estado = Estado.objects.get(nombre='Archivada')
        self.tarea.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Feedback para Tarea: {self.tarea.objetivo} - Aprobado: {"Sí" if self.aprobado else "No"}'

mant_preventivo/models.py
from django.db import models
from django.contrib.auth.models import User

class MantenimientoPreventivo(models.Model):
    tarea_mantenimiento = models.OneToOneField('TareaMantenimiento', on_delete=models.CASCADE, related_name='informe_mantenimiento', blank=True, null=True)
    tipo_ot = models.CharField(max_length=30, blank=False, null=True)
    asignado_a = models.ForeignKey(User, on_delete=models.CASCADE, related_name='asignado_mantenimiento', blank=True, null=True)
    solicitante = models.CharField(max_length=300, blank=False, null=True)
    prioridad = models.CharField(max_length=50, choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')])
    programado_para = models.DateField(max_length=50, blank=False, null=True)
    turno = models.CharField(max_length=50, choices=[('Dia', 'Dia'), ('Noche', 'Noche')])
    descripcion_trabajo = models.TextField( blank=False, null=True)
    cod_equipo = models.CharField(max_length=50, blank=False, null=True)
    equipo = models.CharField(max_length=50, blank=False, null=True)
    observaciones = models.TextField(blank=True, null=True, default='No se han registrado observaciones')
    realizado_por = models.CharField(max_length=30, blank=True, null=True)
    supervisor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='supervisado_por', blank=True)
    fecha = models.DateTimeField(auto_now_add=True)
    ultima_modificacion = models.DateTimeField(auto_now=True)
    tabla_dinamica = models.JSONField(default=list)


class TareaMantenimiento(models.Model):
    estado = models.CharField(max_length=50, choices=[('En Curso', 'En Curso'), ('Revision', 'Revision'), ('Archivada', 'Archivada')], default= 'En Curso')
    asignado_a = models.ForeignKey(User, on_delete=models.CASCADE, related_name='asignado_tarea')
    creada = models.DateTimeField(auto_now_add=True)
    ultima_modificacion = models.DateTimeField(auto_now=True)
    creado_por = models.ForeignKey(User, on_delete=models.CASCADE, related_name='creador')
    supervisor = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='supervisor_tarea', blank=True)
    tipo_ot = models.CharField(max_length=30, blank=False, null=True)
    descripcion_trabajo = models.TextField(blank=False, null=True)

app/templates/app/infraestructura/Informe.html
{% extends '../base.html' %}

{% block content %}
<div class="container mt-9 text-white">
    <h2 class="mb-4">Crear Informe</h2>
    <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}

        <!-- Campo de zona -->
        <div class="md-form">
            {{ form.zona.label_tag }}
            {{ form.zona }}
            <div class="invalid-feedback">
                {% for error in form.zona.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>
        <!-- Campo de tipo de informe -->
        <div class="md-form">
            {{ form.categoría.label_tag }}
            {{ form.categoría }}
            <div class="invalid-feedback">
                {% for error in form.categoría.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Campo de ubicación técnica -->
        <div class="md-form" id="ubicacion_tecnica_field" style="display: none;">
            {{ form.ubicacion_tecnica.label_tag }}
            <select id="id_ubicacion_tecnica" name="ubicacion_tecnica" class="form-control">
                <option value="">Seleccione una ubicación técnica</option>
            </select>
            <div class="invalid-feedback">
                {% for error in form.ubicacion_tecnica.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Campo de equipo -->
        <div class="md-form" id="equipo_field" style="display: none;">
            {{ form.equipo.label_tag }}
            <select id="id_equipo" name="equipo" class="form-control">
                <option value="">Seleccione un equipo</option>
            </select>
            <div class="invalid-feedback">
                {% for error in form.equipo.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Campo de objetivo -->
        <div class="md-form">
            {{ form.objetivo.label_tag }}
            {{ form.objetivo }}
            <div class="invalid-feedback">
                {% for error in form.objetivo.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Campo de mensaje -->
        <div class="md-form">
            {{ form.mensaje.label_tag }}
            {{ form.mensaje }}
            <div class="invalid-feedback">
                {% for error in form.mensaje.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
        </div>

        <!-- Campo de imagen -->
        <div class="md-form">
            {{ form.imagen.label_tag }}
            {{ form.imagen }}
            <div class="invalid-feedback">
                {% for error in form.imagen.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <!-- Vista previa de la imagen -->
            <div>
                <img id="imagen-preview" src="#" alt="Vista previa de la imagen" style="display: none; max-width: 100%; height: auto; margin-top: 10px;">
            </div>
        </div>
        
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</div>

<script>
    const imageInput = document.getElementById('id_imagen');  // Seleccionamos el input de archivo
    const imagePreview = document.getElementById('imagen-preview');  // Vista previa de la imagen

    if (imageInput) {
        imageInput.addEventListener('change', function (event) {
            const file = event.target.files[0];  // Obtenemos el archivo seleccionado
            if (file) {
                const fileType = file.type.split('/')[0];  // Verificamos que sea una imagen
                if (fileType === 'image') {
                    const reader = new FileReader();  // Creamos un nuevo FileReader
                    reader.onload = function (e) {
                        // Cuando el archivo se haya leído, lo asignamos como src del preview
                        imagePreview.src = e.target.result;
                        imagePreview.style.display = 'block';  // Mostramos la imagen previa
                    };
                    reader.readAsDataURL(file);  // Leemos el archivo como una URL de datos
                } else {
                    // Si no es una imagen, mostramos un mensaje de error
                    alert('Tipo de archivo no válido. Por favor selecciona una imagen.');
                    imageInput.value = '';  // Limpiamos el campo
                    imagePreview.style.display = 'none';  // Ocultamos la vista previa
                }
            }
        });
    }

    // Función para cargar ubicaciones técnicas basadas en la zona seleccionada
    function cargarUbicacionesTecnicas(zonaId) {
        const ubicacionTecnicaField = document.getElementById('ubicacion_tecnica_field');
        const ubicacionTecnicaSelect = document.getElementById('id_ubicacion_tecnica');
        ubicacionTecnicaSelect.innerHTML = '<option value="">Seleccione una ubicación técnica</option>';

        if (zonaId) {
            fetch(`api/ubicaciones-tecnicas/?zona_id=${zonaId}`)
                .then(response => response.json())
                .then(data => {
                    data.forEach(ubicacion => {
                        const option = document.createElement('option');
                        option.value = ubicacion.id;
                        option.textContent = `${ubicacion.codigo} (${ubicacion.descripcion})`;
                        ubicacionTecnicaSelect.appendChild(option);
                    });
                    ubicacionTecnicaField.style.display = 'block';
                });
        } else {
            ubicacionTecnicaField.style.display = 'none';
        }
    }

    // Función para cargar equipos basados en la ubicación técnica seleccionada
    function cargarEquipos(ubicacionTecnicaId) {
        const equipoField = document.getElementById('equipo_field');
        const equipoSelect = document.getElementById('id_equipo');
        equipoSelect.innerHTML = '<option value="">Seleccione un equipo</option>';

        if (ubicacionTecnicaId) {
            fetch(`api/equipos/?ubicacion_tecnica_id=${ubicacionTecnicaId}`)
                .then(response => response.json())
                .then(data => {
                    data.forEach(equipo => {
                        const option = document.createElement('option');
                        option.value = equipo.id;
                        option.textContent = `${equipo.codigo} (${equipo.descripcion})`;
                        equipoSelect.appendChild(option);
                    });
                    equipoField.style.display = 'block';
                });
        } else {
            equipoField.style.display = 'none';
        }
    }

    // Función para mostrar/ocultar campos basados en la categoría seleccionada
    function mostrarCamposPorCategoria(categoria) {
        const ubicacionTecnicaField = document.getElementById('ubicacion_tecnica_field');
        const equipoField = document.getElementById('equipo_field');

        if (categoria === 'INF') {
            ubicacionTecnicaField.style.display = 'block';
            equipoField.style.display = 'none';
        } else if (categoria === 'MAQ') {
            ubicacionTecnicaField.style.display = 'block';
            equipoField.style.display = 'block';
        } else {
            ubicacionTecnicaField.style.display = 'none';
            equipoField.style.display = 'none';
        }
    }

    // Event listener para el cambio en el selector de zona
    document.getElementById('id_zona').addEventListener('change', function() {
        const zonaId = this.value;
        cargarUbicacionesTecnicas(zonaId);
    });

    // Event listener para el cambio en el selector de ubicación técnica
    document.getElementById('id_ubicacion_tecnica').addEventListener('change', function() {
        const ubicacionTecnicaId = this.value;
        cargarEquipos(ubicacionTecnicaId);
    });

    // Event listener para el cambio en el selector de categoría
    document.getElementById('id_categoría').addEventListener('change', function() {
        const categoria = this.value;
        mostrarCamposPorCategoria(categoria);
    });

    // Inicializar la visibilidad de los campos basados en la categoría seleccionada al cargar la página
    document.addEventListener('DOMContentLoaded', function() {
        const categoria = document.getElementById('id_categoría').value;
        mostrarCamposPorCategoria(categoria);
    });
</script>
{% endblock %}

app/templates/app/infraestructura/crear_solicitud.html
{% extends "../base.html" %}
{% block content %}

<div class="container mt-9 text-white">
    <h2 class="mb-4">Solicitud Externo</h2>
    <form method="POST" enctype="multipart/form-data" class="needs-validation" novalidate>
        {% csrf_token %}
        <div class="form-group">
            {{ form.non_field_errors }}
            {{ form.externo.label_tag }}
            {{ form.externo }}
            {{ form.externo.errors }}
        </div>
        <div class="form-group">
            <label for="email">Correo Electrónico</label>
            <input type="email" id="email" class="form-control" readonly>
        </div>
        <div class="form-group">
            {{ form.objetivo.label_tag }}
            {{ form.objetivo }}
            {{ form.objetivo.errors }}
        </div>
        <div class="form-group">
            {{ form.descripcion.label_tag }}
            {{ form.descripcion }}
            {{ form.descripcion.errors }}
        </div>
        <div class="md-form">
            {{ form.imagen.label_tag }}
            {{ form.imagen }}
            <div class="invalid-feedback">
                {% for error in form.imagen.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <div>
                <img id="imagen-preview" src="#" alt="Vista previa de la imagen" style="display: none; max-width: 100%; height: auto; margin-top: 10px;">
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Enviar Solicitud</button>
    </form>
</div>

<script>
    document.getElementById('id_externo').addEventListener('change', function() {
        var userId = this.value;
        fetch(`/externos/api/user/${userId}/`)
            .then(response => {
                if (!response.ok) {
                    throw new Error('Network response was not ok');
                }
                return response.json();
            })
            .then(data => {
                document.getElementById('email').value = data.email;
            })
            .catch(error => {
                console.error('There was a problem with the fetch operation:', error);
                alert('Error al obtener los datos del usuario.');
            });
    });

    const imageInput = document.getElementById('id_imagen');
    const imagePreview = document.getElementById('imagen-preview');

    if (imageInput) {
        imageInput.addEventListener('change', function (event) {
            const file = event.target.files[0]; 
            if (file) {
                const fileType = file.type.split('/')[0];  // Verificamos que sea una imagen
                if (fileType === 'image') {
                    const reader = new FileReader();  // Creamos un nuevo FileReader
                    reader.onload = function (e) {
                        // Cuando el archivo se haya leído, lo asignamos como src del preview
                        imagePreview.src = e.target.result;
                        imagePreview.style.display = 'block';  // Mostramos la imagen previa
                    };
                    reader.readAsDataURL(file);  // Leemos el archivo como una URL de datos
                } else {
                    // Si no es una imagen, mostramos un mensaje de error
                    alert('Tipo de archivo no válido. Por favor selecciona una imagen.');
                    imageInput.value = '';  // Limpiamos el campo
                    imagePreview.style.display = 'none';  // Ocultamos la vista previa
                }
            }
        });
    }
</script>

{% endblock %}

app/templates/app/infraestructura/feedback.html
{% extends "../base.html" %}

{% block content %}
<div class="container mt-9 text-white">
    <h2 class="mb-4">Feedback de la Tarea: {{ tarea.objetivo }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Enviar Feedback</button>
    </form>
    
</div>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const aprobadoRadios = document.querySelectorAll('input[name="aprobado"]');
            const comentarioField = document.querySelector('textarea[name="comentarios"]').parentElement;
            
            // Ocultar el campo de comentario por defecto
            comentarioField.style.display = 'none';

            function toggleComentarioField() {
                const aprobadoValue = document.querySelector('input[name="aprobado"]:checked').value;
                if (aprobadoValue === 'True') {
                    comentarioField.style.display = 'none';
                } else {
                    comentarioField.style.display = 'block';
                }
            }

            aprobadoRadios.forEach(radio => {
                radio.addEventListener('change', toggleComentarioField);
            });
            toggleComentarioField();  // Inicializar el estado del campo comentario
        });
    </script>
{% endblock %}

app/templates/app/infraestructura/presupuesto.html
{% extends '../base.html' %}

{% block content %}
<div class="container mt-9 text-white">

    <h2>Cargar Presupuesto:  {{ solicitud.objetivo }}</h2>
    
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_pdf_presupuesto">Cargar Presupuesto (PDF):</label>
            {{ form.archivo }}
            {% if form.archivo.errors %}
                <div class="text-danger">{{ form.archivo.errors }}</div>
            {% endif %}
        </div>
        <div class="form-group">
            <label for="id_estado">Estado:</label>
            {{ form.estado }}
            {% if form.estado.errors %}
                <div class="text-danger">{{ form.estado.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Campo Razón de Rechazo -->
        <div class="form-group">
            <label for="id_mensaje">Mensaje:</label>
            {{ form.mensaje }}
            {% if form.mensaje.errors %}
                <div class="text-danger">{{ form.mensaje.errors }}</div>
            {% endif %}
        </div>
        
        <!-- Campo Fecha de Asistencia -->
        <div class="form-group">
            <label for="id_fecha_asistencia">Fecha de Asistencia:</label>
            {{ form.fecha_asistencia }}
            {% if form.fecha_asistencia.errors %}
                <div class="text-danger">{{ form.fecha_asistencia.errors }}</div>
            {% endif %}
        </div>
    
        <button type="submit" class="btn btn-primary">Guardar</button>
    </form>
</div>
{% endblock %}