Lab_Bago/urls.py
from django.contrib import admin
from django.urls import path, include

def trigger_error(request):
    division_by_zero = 1 / 0

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    path('auth/', include('authentication.urls')),
    path('externos/', include('external_workers.urls')),
    path('internos/', include('internal_workers.urls')),
    path('mant_preventivo/', include('mant_preventivo.urls')),
    path('sentry-debug/', trigger_error),
]

app/urls.py
from django.urls import path
from django.conf.urls import handler404
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from axes.decorators import axes_dispatch


urlpatterns = [
    path('', home, name="home"),
    path('base/', base, name="base"),
    #path('logout/', cerrar_session, name="logout"),

    #path('auth/login/', axes_dispatch(iniciar_session), name="login"),
    #path('auth/registro/', registro, name="registro"),
    path('auth/roles/', roles, name='roles'),
    





    #path('infraestructura/crear_solicitud/', crear_solicitud_externo, name='crear_solicitud'),
    #path('infraestructura/presupuesto/<int:tarea_id>/', cargar_presupuesto, name='gestionar_presupuesto'),
    #path('infraestructura/reporte_externo/<int:tarea_id>/', reporte_externo, name='reporte_externo'),
    #path('infraestructura/feedback_externo/<int:tarea_id>/', feedback_externo, name='feedback_externo'),

    #path('api/user/<int:user_id>/', obtener_datos_usuario, name='obtener_datos_usuario'),

    path('dashboard/graficos', graficos, name='graficos'),
    path('descargar-tareas/', descargar_tareas, name='descargar_tareas'),

    #path('dashboard/listar_tareas', listar_tareas, name='listar_tareas'),
    #path('dashboard/listar_solicitudes', listar_solicitudes, name='listar_solicitudes'),

    #path('notificaciones/', notificaciones, name='notificaciones'),
    #path('notificaciones/<int:notificaciones_id>/', notificaciones_id , name='notificaciones_id'),
    #path('notificacion/marcar_leida/<int:notificacion_id>/', marcar_notificacion_leida, name='marcar_notificacion_leida'),



    #path('detalle/informe/<int:informe_id>/', detalle_informe, name='detalle_informe'),
    #path('detalle/reporte/<int:reporte_id>/', detalle_reporte, name='detalle_reporte'),
    #path('detalle/feedback/<int:feedback_id>/', detalle_feedback, name='detalle_feedback'),

    #path('detalle_externo/solicitud/<int:solicitud_id>/', detalle_solicitud, name='detalle_solicitud'),
    #path('detalle_externo/presupuesto_ext/<int:presupuesto_id>/', detalle_presupuesto, name='detalle_presupuesto'),
    #path('detalle_externo/reporte_ext/<int:reporte_ex_id>/', detalle_reporte_ex, name='detalle_reporte_ext'),
    #path('detalle_externo/feedback_ext/<int:feedback_ex_id>/', detalle_feedbacks_ex, name='detalle_feedback_ext'),

    path('app/error/404', error_404, name='error_404'),
    path('app/error/403', error_403, name='error_403'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


handler404 = error_404
handler403 = error_403

internal_workers/models.py
from django.db import models
from django.contrib.auth.models import User

class Zona(models.Model):
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre
    
class UbicacionTecnica(models.Model):
    zona = models.ForeignKey(Zona, related_name='ubicaciones_tecnicas', on_delete=models.CASCADE)
    codigo = models.CharField(max_length=255)
    descripcion = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.codigo} ({self.descripcion})"

class Equipo(models.Model):
    ubicacion_tecnica = models.ForeignKey(UbicacionTecnica, related_name='equipos', on_delete=models.CASCADE)
    codigo = models.CharField(max_length=255)
    descripcion = models.TextField(null=True, blank=True)


    def __str__(self):
        return f"{self.codigo} ({self.descripcion})"


class Estado(models.Model):
    nombre = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.nombre

class Informe(models.Model):
    INFRAESTRUCTURA = 'INF'
    MAQUINARIA = 'MAQ'
    CATEGORIA_CHOICES = [
        (INFRAESTRUCTURA, 'Infraestructura'),
        (MAQUINARIA, 'Maquinaria'),
    ]

    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="informes")
    creado_en = models.DateTimeField(auto_now_add=True)
    zona = models.ForeignKey(Zona, on_delete=models.SET_NULL, null=True)
    objetivo = models.TextField(null=True, blank=True)
    mensaje = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='informes/')
    categoría = models.CharField(max_length=3, choices=CATEGORIA_CHOICES, default=INFRAESTRUCTURA)
    ubicacion_tecnica = models.ForeignKey(UbicacionTecnica, on_delete=models.SET_NULL, null=True, blank=True)
    equipo = models.ForeignKey(Equipo, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        ordering = ['-creado_en']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if not Tarea.objects.filter(informe=self).exists():
            Tarea.objects.create(informe=self, objetivo=self.objetivo)

    def __str__(self):
        return f'Informe: {self.objetivo}'

class Notificacion(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    informe = models.ForeignKey(Informe, on_delete=models.CASCADE)
    leido = models.BooleanField(default=False)
    creado_en = models.DateTimeField(auto_now_add=True)
    mensaje = models.TextField(null=True, blank=True)

    def marcar_como_leido(self):
        self.leido = True
        self.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Tarea(models.Model):
    informe = models.ForeignKey(Informe, on_delete=models.CASCADE)
    objetivo = models.TextField(null=True, blank=True)
    estado = models.ForeignKey(Estado, on_delete=models.SET_NULL, null=True, blank=True)
    asignado_a = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name="tareas")
    creado_en = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.estado:
            self.estado = Estado.objects.get(nombre='Pendiente')
        self.objetivo = self.informe.objetivo
        super().save(*args, **kwargs)

    def asignar_tecnico(self, tecnico):
        if self.asignado_a:
            Notificacion.objects.create(usuario=self.asignado_a, informe=self.informe, mensaje=f'Tarea reasignada: {self.objetivo}')
        
        self.asignado_a = tecnico
        self.save()
        Notificacion.objects.create(usuario=tecnico, informe=self.informe, mensaje=f'Tarea asignada: {self.objetivo}')

    def __str__(self):
        return f'Tarea: {self.objetivo} - Estado: {self.estado}'

class ReporteTarea(models.Model):
    tarea = models.OneToOneField(Tarea, on_delete=models.CASCADE, related_name='reporte_tarea')
    contenido = models.TextField(null=True, blank=True)
    imagen = models.ImageField(upload_to='reportes_tarea/', blank=False)
    creado_en = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        self.tarea.estado = Estado.objects.get(nombre='Completada')
        self.tarea.save()
        super().save(*args, **kwargs)
        Notificacion.objects.create(
            usuario=self.tarea.informe.usuario,
            informe=self.tarea.informe,
            mensaje=f'Se ha creado un reporte para la tarea: {self.tarea.objetivo}'
        )

    def __str__(self):
        return f'Reporte de Tarea: {self.tarea.objetivo} - Fecha: {self.creado_en.strftime("%Y-%m-%d %H:%M")}'

class FeedbackTarea(models.Model):
    tarea = models.OneToOneField(Tarea, on_delete=models.CASCADE)
    aprobado = models.BooleanField()
    comentarios = models.TextField(null=False, blank=True, default="Trabajo aprobado")
    creado_en = models.DateTimeField(auto_now_add=True)
    creado_por = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.aprobado:
            self.tarea.estado = Estado.objects.get(nombre='Rechazada')
        else:
            self.tarea.estado = Estado.objects.get(nombre='Archivada')
        self.tarea.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return f'Feedback para Tarea: {self.tarea.objetivo} - Aprobado: {"Sí" if self.aprobado else "No"}'

app/templates/app/detalle/feedback.html
{% extends '../base.html' %}

{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <a href="{% url 'listar_tareas' %}" class="btn btn-secondary">
            &#8592; Volver a Listar Tareas
        </a>
        <h1>Detalles Feedback</h1>
    </div>
    <div class="card-body">
        <p><strong>Creador:</strong> {{ feedback.creado_por }}</p>
        <p><strong>Conforme:</strong> {% if feedback.aprobado %}Sí{% else %}No{% endif %}</p>
        <p><strong>Razon:</strong> {{ feedback.comentarios }}</p>
        <p><strong>Fecha de Creación:</strong> {{ feedback.creado_en }}</p>
    </div>
</div>
{% endblock %}

app/templates/app/detalle/informe.html
{% extends '../base.html' %}

{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <a href="{% url 'listar_tareas' %}" class="btn btn-secondary">
            &#8592; Volver a Listar Tareas
        </a>
        <h1>Detalles Informe</h1>
    </div>
    <div class="card-body">
        <p><strong>Creado:</strong> {{ informe.usuario.username }}</p>
        <p><strong>Zona:</strong> {{ informe.zona.nombre }}</p>
        <p><strong>Categoría:</strong> {{ informe.get_categoría_display }}</p>
        {% if informe.categoría == 'INF' %}
            <p><strong>Ubicación Técnica:</strong> {{ informe.ubicacion_tecnica.descripcion }}</p>
        {% elif informe.categoría == 'MAQ' %}
            <p><strong>Ubicación Técnica:</strong> {{ informe.ubicacion_tecnica.descripcion }}</p>
            <p><strong>Equipo:</strong> {{ informe.equipo.descripcion }}</p>
        {% endif %}
        <p><strong>Objetivo:</strong> {{ informe.objetivo }}</p>
        <p><strong>Mensaje:</strong> {{ informe.mensaje }}</p>
        <div class="text-center">
            <img src="{{ informe.imagen.url }}" alt="Imagen del Informe" class="img-fluid" style="width: 600px; height: 500px;">
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/detalle/reporte.html
{% extends '../base.html' %}

{% block content %}
<div class="card mt-4">
    <div class="card-header">
        <a href="{% url 'listar_tareas' %}" class="btn btn-secondary">
            &#8592; Volver a Listar Tareas
        </a>
        <h1>Detalles Reporte</h1>
    </div>
    <div class="card-body">
        <p><strong>Creado por:</strong> {{ reporte.usuario.username }}</p>
        <p><strong>Objetivo:</strong> {{ reporte.tarea.objetivo }}</p>
        <p><strong>Fecha de Creación:</strong> {{ reporte.creado_en }}</p>
        <p><strong>Contenido:</strong> {{ reporte.contenido }}</p>
        <div class="text-center">
            <img src="{{ reporte.imagen.url }}" alt="Imagen del Reporte" class="img-fluid" style="width: 600px; height: 500px;">
        </div>
    </div>
</div>
{% endblock %}